blockchain:
  # difficulty. don't make this lower than 16.
  mine_difficulty_value: 16
  # verifying bits upon PoK verification. higher bits bring higher security. but never make this value bigger than mine_difficulty_value
  verify_bit: 8
  # mining reward
  token_reward_num: 10
  # start mining when this number is reached
  trade_pool_length: 2
  # log directory
  log_path: "./"
  # directory for mnemonicwords
  chinese_mnemonic_path: "./chinese_mnemonic_world.txt"
network:
  # local monitoring IP
  listen_host: "127.0.0.1"
  # local monitoring port
  listen_port: "6666"
  # unique identifier of node group(nodes can only discover each other in the same group)
  rendezvous_string: "pok"
  # nodes only send data to the nodes with the same protocol id.
  protocol_id: "/chain/1.1.0"

