blockchain:
  #difficulty
  mine_difficulty_value: 16
  #mining reward
  token_reward_num: 25
  #交易池大小(满足多少条交易才开始进行挖矿)
  trade_pool_length: 2
  #日志存放路径
  log_path: "./"
  #中文助记词种子路径
  chinese_mnemonic_path: "./chinese_mnemonic_world.txt"
network:
  #local monitoring IP
  listen_host: "127.0.0.1"
  #local monitoring port
  listen_port: "9000"
  #unique identifier of node group(如果节点间名称不同会找不到网络)
  rendezvous_string: "pok"
  #网络传输流的协议id(如果节点间id不同发送不了数据)
  protocol_id: "/chain/1.1.0"

